title: Z1 Internal Development
description: Internal iOS distribution for Z1 app.
url: "https://z1-internal-development.netlify.app"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

timezone: Asia/Phnom_Penh
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

zpoin: /zpoin

z1: /z1